# Generated by Django 4.1.5 on 2023-01-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('level', models.CharField(max_length=55)),
                ('ability', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=55)),
                ('equipment', models.CharField(max_length=55)),
                ('spells', models.CharField(max_length=55)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitDie', models.CharField(max_length=55)),
                ('saves', models.CharField(max_length=55)),
                ('class_description', models.CharField(max_length=55)),
                ('classes_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=55)),
                ('weapon_type', models.CharField(max_length=55)),
                ('weapon_description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=55)),
                ('race_description', models.CharField(max_length=55)),
                ('ability_increase', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='charclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.character')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.classes')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='classes_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.classes'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.user'),
        ),
    ]
