# Generated by Django 4.1.5 on 2023-01-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonapi.equipment'),
        ),
    ]
