# Generated by Django 4.1.5 on 2023-01-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonapi', '0002_alter_character_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='classes_name',
        ),
        migrations.AlterField(
            model_name='charclass',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_classes', to='dragonapi.character'),
        ),
    ]
